export const JUMBOTRON_CLICKED = "JUMBOTRON_CLICKED";
export const CLOSE_JUMBOTRON_MODAL = "CLOSE_JUMBOTRON_MODAL";
export const TIMER_START = "TIMER_START";
export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const CLOSE_SUCCESS_SCREEN = "CLOSE_SUCCESS_SCREEN";
export const CALL_PATIENT = "CALL_PATIENT";
export const PATIENT_SERVED = "PATIENT_SERVED";
export const ADD_VISIT_TIME = "ADD_VISIT_TIME";
export const PATIENT_SAVE_START = "PATIENT_SAVE_START";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const RESET_ERROR = "RESET_ERROR";
export const LOGOUT = "LOGOUT";
export const CHECK_SPECIALIST_FAIL = "CHECK_SPECIALIST_FAIL";
export const CHECK_SPECIALIST_SUCCESS = "CHECK_SPECIALIST_SUCCESS";