export const JUMBOTRON_CLICKED = "JUMBOTRON_CLICKED";
export const CLOSE_JUMBOTRON_MODAL = "CLOSE_JUMBOTRON_MODAL";
export const TIMER_START = "TIMER_START";
export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const CLOSE_SUCCESS_SCREEN = "CLOSE_SUCCESS_SCREEN";